# Build stage
FROM golang:1.25.6@sha256:ce63a16e0f7063787ebb4eb28e72d477b00b4726f79874b3205a965ffd797ab2 AS builder

WORKDIR /go/src
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go install github.com/bufbuild/buf/cmd/buf@v1.56.0 && \
  go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.27.1 && \
  go install google.golang.org/grpc/cmd/protoc-gen-go-grpc && \
  go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.27.1 && \
  go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.7
RUN make buf

RUN apt update && apt install zip unzip -y
RUN make update-swagger

ENV CGO_ENABLED=0
RUN go build -cover -o /go/bin/chall-manager cmd/chall-manager/main.go



# Prod stage
FROM pulumi/pulumi-go:3.225.1@sha256:6a5d6bce087e41c48d74c086357167747343eeaf4ee50f189a8adac2766c6349
RUN pulumi login --local
COPY --from=builder /go/bin/chall-manager /chall-manager
COPY ./gen ./gen
ENTRYPOINT [ "/chall-manager" ]
