# Build stage
FROM golang:1.26.1@sha256:c7e98cc0fd4dfb71ee7465fee6c9a5f079163307e4bf141b336bb9dae00159a5 AS builder

WORKDIR /go/src
COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=0
RUN go build -cover -o /go/bin/chall-manager-janitor cmd/chall-manager-janitor/main.go



# Prod stage
FROM scratch
COPY --from=builder /go/bin/chall-manager-janitor /chall-manager-janitor
ENTRYPOINT [ "/chall-manager-janitor" ]
