# Build stage
FROM golang:1.25.6@sha256:06d1251c59a75761ce4ebc8b299030576233d7437c886a68b43464bad62d4bb1 AS builder

WORKDIR /go/src
COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=0
RUN go build -cover -o /go/bin/chall-manager-janitor cmd/chall-manager-janitor/main.go



# Prod stage
FROM scratch
COPY --from=builder /go/bin/chall-manager-janitor /chall-manager-janitor
ENTRYPOINT [ "/chall-manager-janitor" ]
