# Build stage
FROM golang:1.25.6@sha256:06d1251c59a75761ce4ebc8b299030576233d7437c886a68b43464bad62d4bb1 AS builder

WORKDIR /go/src
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go install github.com/bufbuild/buf/cmd/buf@v1.56.0 && \
    go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.27.1 && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc && \
    go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.27.1 && \
    go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.7
RUN make buf

RUN apt update && apt install zip unzip -y
RUN make update-swagger

ENV CGO_ENABLED=0
RUN go build -cover -o /go/bin/chall-manager cmd/chall-manager/main.go



# Prod stage
FROM pulumi/pulumi-go:3.216.0@sha256:732de57bc2bde08561ef98921995ba0746629e69fc5ebf83341ff3efa529a64f
RUN pulumi login --local
COPY --from=builder /go/bin/chall-manager /chall-manager
COPY ./gen ./gen
ENTRYPOINT [ "/chall-manager" ]
