// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/v1/instance/instance.proto

package instance

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateInstanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The challenge identifier
	ChallengeId string `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	// The source (user/team) identifier.
	SourceId string `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// A key=value additional configuration to pass to the instance when created.
	Additional    map[string]string `protobuf:"bytes,3,rep,name=additional,proto3" json:"additional,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstanceRequest) Reset() {
	*x = CreateInstanceRequest{}
	mi := &file_api_v1_instance_instance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceRequest) ProtoMessage() {}

func (x *CreateInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_instance_instance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceRequest.ProtoReflect.Descriptor instead.
func (*CreateInstanceRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_instance_instance_proto_rawDescGZIP(), []int{0}
}

func (x *CreateInstanceRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *CreateInstanceRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *CreateInstanceRequest) GetAdditional() map[string]string {
	if x != nil {
		return x.Additional
	}
	return nil
}

type RetrieveInstanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The challenge identifier
	ChallengeId string `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	// The source (user/team) identifier.
	SourceId      string `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrieveInstanceRequest) Reset() {
	*x = RetrieveInstanceRequest{}
	mi := &file_api_v1_instance_instance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrieveInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveInstanceRequest) ProtoMessage() {}

func (x *RetrieveInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_instance_instance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveInstanceRequest.ProtoReflect.Descriptor instead.
func (*RetrieveInstanceRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_instance_instance_proto_rawDescGZIP(), []int{1}
}

func (x *RetrieveInstanceRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *RetrieveInstanceRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type QueryInstanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The source (user/team) identifier.
	SourceId      string `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryInstanceRequest) Reset() {
	*x = QueryInstanceRequest{}
	mi := &file_api_v1_instance_instance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryInstanceRequest) ProtoMessage() {}

func (x *QueryInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_instance_instance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryInstanceRequest.ProtoReflect.Descriptor instead.
func (*QueryInstanceRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_instance_instance_proto_rawDescGZIP(), []int{2}
}

func (x *QueryInstanceRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type RenewInstanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The challenge identifier
	ChallengeId string `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	// The source (user/team) identifier.
	SourceId      string `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewInstanceRequest) Reset() {
	*x = RenewInstanceRequest{}
	mi := &file_api_v1_instance_instance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewInstanceRequest) ProtoMessage() {}

func (x *RenewInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_instance_instance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewInstanceRequest.ProtoReflect.Descriptor instead.
func (*RenewInstanceRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_instance_instance_proto_rawDescGZIP(), []int{3}
}

func (x *RenewInstanceRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *RenewInstanceRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type DeleteInstanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The challenge identifier
	ChallengeId string `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	// The source (user/team) identifier.
	SourceId      string `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInstanceRequest) Reset() {
	*x = DeleteInstanceRequest{}
	mi := &file_api_v1_instance_instance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInstanceRequest) ProtoMessage() {}

func (x *DeleteInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_instance_instance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInstanceRequest.ProtoReflect.Descriptor instead.
func (*DeleteInstanceRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_instance_instance_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteInstanceRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *DeleteInstanceRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

// The challenge instance object that the chall-manager exposes.
// Notice it differs from the internal representation, as it handles
// filesystem-related information.
type Instance struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The challenge identifier
	ChallengeId string `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	// The source (user/team) identifier.
	SourceId string `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// The time since when the instance is running.
	Since *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=since,proto3" json:"since,omitempty"`
	// The last time the instance has been renewed.
	LastRenew *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_renew,json=lastRenew,proto3" json:"last_renew,omitempty"`
	// The time the instance will "die" i.e. be destroyed by the janitor.
	Until *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=until,proto3,oneof" json:"until,omitempty"`
	// The connection information that is given to the players in order
	// to reach their instance.
	ConnectionInfo string `protobuf:"bytes,6,opt,name=connection_info,json=connectionInfo,proto3" json:"connection_info,omitempty"`
	// If specified, the flag that validates the challenge instance.
	// This avoids shareflag, but don't block sharing solving strategy/write-up.
	// DEPRECATED: #950 showed the need for multiple flags, so please migrate to it.
	//
	// Deprecated: Marked as deprecated in api/v1/instance/instance.proto.
	Flag *string `protobuf:"bytes,7,opt,name=flag,proto3,oneof" json:"flag,omitempty"`
	// A list of flags that validates the challenge instance.
	// This avoids shareflag, but don't block sharing solving strategy/write-up.
	Flags []string `protobuf:"bytes,9,rep,name=flags,proto3" json:"flags,omitempty"`
	// A key=value additional configuration to pass to the instance when created.
	Additional    map[string]string `protobuf:"bytes,8,rep,name=additional,proto3" json:"additional,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_api_v1_instance_instance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_instance_instance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_api_v1_instance_instance_proto_rawDescGZIP(), []int{5}
}

func (x *Instance) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *Instance) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Instance) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *Instance) GetLastRenew() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRenew
	}
	return nil
}

func (x *Instance) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

func (x *Instance) GetConnectionInfo() string {
	if x != nil {
		return x.ConnectionInfo
	}
	return ""
}

// Deprecated: Marked as deprecated in api/v1/instance/instance.proto.
func (x *Instance) GetFlag() string {
	if x != nil && x.Flag != nil {
		return *x.Flag
	}
	return ""
}

func (x *Instance) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *Instance) GetAdditional() map[string]string {
	if x != nil {
		return x.Additional
	}
	return nil
}

type DownloadCapturesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The challenge identifier
	ChallengeId string `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	// The source (user/team) identifier.
	SourceId      string `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadCapturesRequest) Reset() {
	*x = DownloadCapturesRequest{}
	mi := &file_api_v1_instance_instance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadCapturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadCapturesRequest) ProtoMessage() {}

func (x *DownloadCapturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_instance_instance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadCapturesRequest.ProtoReflect.Descriptor instead.
func (*DownloadCapturesRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_instance_instance_proto_rawDescGZIP(), []int{6}
}

func (x *DownloadCapturesRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *DownloadCapturesRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type CaptureChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chunk of tarball data
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureChunk) Reset() {
	*x = CaptureChunk{}
	mi := &file_api_v1_instance_instance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureChunk) ProtoMessage() {}

func (x *CaptureChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_instance_instance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureChunk.ProtoReflect.Descriptor instead.
func (*CaptureChunk) Descriptor() ([]byte, []int) {
	return file_api_v1_instance_instance_proto_rawDescGZIP(), []int{7}
}

func (x *CaptureChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListCaptureSessionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The challenge identifier
	ChallengeId string `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	// The source (user/team) identifier.
	SourceId      string `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCaptureSessionsRequest) Reset() {
	*x = ListCaptureSessionsRequest{}
	mi := &file_api_v1_instance_instance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCaptureSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCaptureSessionsRequest) ProtoMessage() {}

func (x *ListCaptureSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_instance_instance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCaptureSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListCaptureSessionsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_instance_instance_proto_rawDescGZIP(), []int{8}
}

func (x *ListCaptureSessionsRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ListCaptureSessionsRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type ListCaptureSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*CaptureSessionInfo  `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCaptureSessionsResponse) Reset() {
	*x = ListCaptureSessionsResponse{}
	mi := &file_api_v1_instance_instance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCaptureSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCaptureSessionsResponse) ProtoMessage() {}

func (x *ListCaptureSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_instance_instance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCaptureSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListCaptureSessionsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_instance_instance_proto_rawDescGZIP(), []int{9}
}

func (x *ListCaptureSessionsResponse) GetSessions() []*CaptureSessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type CaptureSessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Container     string                 `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	FilePath      string                 `protobuf:"bytes,5,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	FileSize      int64                  `protobuf:"varint,6,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	PacketCount   int64                  `protobuf:"varint,7,opt,name=packet_count,json=packetCount,proto3" json:"packet_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureSessionInfo) Reset() {
	*x = CaptureSessionInfo{}
	mi := &file_api_v1_instance_instance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureSessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureSessionInfo) ProtoMessage() {}

func (x *CaptureSessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_instance_instance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureSessionInfo.ProtoReflect.Descriptor instead.
func (*CaptureSessionInfo) Descriptor() ([]byte, []int) {
	return file_api_v1_instance_instance_proto_rawDescGZIP(), []int{10}
}

func (x *CaptureSessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CaptureSessionInfo) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

func (x *CaptureSessionInfo) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CaptureSessionInfo) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *CaptureSessionInfo) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *CaptureSessionInfo) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *CaptureSessionInfo) GetPacketCount() int64 {
	if x != nil {
		return x.PacketCount
	}
	return 0
}

var File_api_v1_instance_instance_proto protoreflect.FileDescriptor

const file_api_v1_instance_instance_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/v1/instance/instance.proto\x12\x0fapi.v1.instance\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x8c\x02\n" +
	"\x15CreateInstanceRequest\x12-\n" +
	"\fchallenge_id\x18\x01 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\vchallengeId\x12'\n" +
	"\tsource_id\x18\x02 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\bsourceId\x12\\\n" +
	"\n" +
	"additional\x18\x03 \x03(\v26.api.v1.instance.CreateInstanceRequest.AdditionalEntryB\x04\xe2A\x01\x01R\n" +
	"additional\x1a=\n" +
	"\x0fAdditionalEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"q\n" +
	"\x17RetrieveInstanceRequest\x12-\n" +
	"\fchallenge_id\x18\x01 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\vchallengeId\x12'\n" +
	"\tsource_id\x18\x02 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\bsourceId\"?\n" +
	"\x14QueryInstanceRequest\x12'\n" +
	"\tsource_id\x18\x01 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\bsourceId\"n\n" +
	"\x14RenewInstanceRequest\x12-\n" +
	"\fchallenge_id\x18\x01 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\vchallengeId\x12'\n" +
	"\tsource_id\x18\x02 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\bsourceId\"o\n" +
	"\x15DeleteInstanceRequest\x12-\n" +
	"\fchallenge_id\x18\x01 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\vchallengeId\x12'\n" +
	"\tsource_id\x18\x02 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\bsourceId\"\xc5\x04\n" +
	"\bInstance\x12-\n" +
	"\fchallenge_id\x18\x01 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\vchallengeId\x12'\n" +
	"\tsource_id\x18\x02 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\bsourceId\x12<\n" +
	"\x05since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\x05since\x12E\n" +
	"\n" +
	"last_renew\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\tlastRenew\x12A\n" +
	"\x05until\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\n" +
	"\x92A\x03J\x011\xe2A\x01\x01H\x00R\x05until\x88\x01\x01\x123\n" +
	"\x0fconnection_info\x18\x06 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\x0econnectionInfo\x12%\n" +
	"\x04flag\x18\a \x01(\tB\f\x92A\x03J\x011\xe2A\x01\x01\x18\x01H\x01R\x04flag\x88\x01\x01\x12\x1a\n" +
	"\x05flags\x18\t \x03(\tB\x04\xe2A\x01\x01R\x05flags\x12O\n" +
	"\n" +
	"additional\x18\b \x03(\v2).api.v1.instance.Instance.AdditionalEntryB\x04\xe2A\x01\x01R\n" +
	"additional\x1a=\n" +
	"\x0fAdditionalEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_untilB\a\n" +
	"\x05_flag\"q\n" +
	"\x17DownloadCapturesRequest\x12-\n" +
	"\fchallenge_id\x18\x01 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\vchallengeId\x12'\n" +
	"\tsource_id\x18\x02 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x01R\bsourceId\"\"\n" +
	"\fCaptureChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"t\n" +
	"\x1aListCaptureSessionsRequest\x12-\n" +
	"\fchallenge_id\x18\x01 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x02R\vchallengeId\x12'\n" +
	"\tsource_id\x18\x02 \x01(\tB\n" +
	"\x92A\x03J\x011\xe2A\x01\x01R\bsourceId\"^\n" +
	"\x1bListCaptureSessionsResponse\x12?\n" +
	"\bsessions\x18\x01 \x03(\v2#.api.v1.instance.CaptureSessionInfoR\bsessions\"\xa0\x02\n" +
	"\x12CaptureSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1c\n" +
	"\tcontainer\x18\x02 \x01(\tR\tcontainer\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x1b\n" +
	"\tfile_path\x18\x05 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tfile_size\x18\x06 \x01(\x03R\bfileSize\x12!\n" +
	"\fpacket_count\x18\a \x01(\x03R\vpacketCount2\xc6\b\n" +
	"\x0fInstanceManager\x12p\n" +
	"\x0eCreateInstance\x12&.api.v1.instance.CreateInstanceRequest\x1a\x19.api.v1.instance.Instance\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/instance\x12\x8c\x01\n" +
	"\x10RetrieveInstance\x12(.api.v1.instance.RetrieveInstanceRequest\x1a\x19.api.v1.instance.Instance\"3\x82\xd3\xe4\x93\x02-\x12+/api/v1/instance/{challenge_id}/{source_id}\x12m\n" +
	"\rQueryInstance\x12%.api.v1.instance.QueryInstanceRequest\x1a\x19.api.v1.instance.Instance\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/v1/instance0\x01\x12\x89\x01\n" +
	"\rRenewInstance\x12%.api.v1.instance.RenewInstanceRequest\x1a\x19.api.v1.instance.Instance\"6\x82\xd3\xe4\x93\x020:\x01*2+/api/v1/instance/{challenge_id}/{source_id}\x12\x85\x01\n" +
	"\x0eDeleteInstance\x12&.api.v1.instance.DeleteInstanceRequest\x1a\x16.google.protobuf.Empty\"3\x82\xd3\xe4\x93\x02-*+/api/v1/instance/{challenge_id}/{source_id}\x12\xc7\x01\n" +
	"\x10DownloadCaptures\x12(.api.v1.instance.DownloadCapturesRequest\x1a\x1d.api.v1.instance.CaptureChunk\"h\x82\xd3\xe4\x93\x02bZ*\x12(/api/v1/instance/{challenge_id}/captures\x124/api/v1/instance/{challenge_id}/{source_id}/captures0\x01\x12\xe4\x01\n" +
	"\x13ListCaptureSessions\x12+.api.v1.instance.ListCaptureSessionsRequest\x1a,.api.v1.instance.ListCaptureSessionsResponse\"r\x82\xd3\xe4\x93\x02lZ/\x12-/api/v1/instance/{challenge_id}/captures/list\x129/api/v1/instance/{challenge_id}/{source_id}/captures/listB<Z:github.com/ctfer-io/chall-manager/api/v1/instance;instanceb\x06proto3"

var (
	file_api_v1_instance_instance_proto_rawDescOnce sync.Once
	file_api_v1_instance_instance_proto_rawDescData []byte
)

func file_api_v1_instance_instance_proto_rawDescGZIP() []byte {
	file_api_v1_instance_instance_proto_rawDescOnce.Do(func() {
		file_api_v1_instance_instance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_instance_instance_proto_rawDesc), len(file_api_v1_instance_instance_proto_rawDesc)))
	})
	return file_api_v1_instance_instance_proto_rawDescData
}

var file_api_v1_instance_instance_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_v1_instance_instance_proto_goTypes = []any{
	(*CreateInstanceRequest)(nil),       // 0: api.v1.instance.CreateInstanceRequest
	(*RetrieveInstanceRequest)(nil),     // 1: api.v1.instance.RetrieveInstanceRequest
	(*QueryInstanceRequest)(nil),        // 2: api.v1.instance.QueryInstanceRequest
	(*RenewInstanceRequest)(nil),        // 3: api.v1.instance.RenewInstanceRequest
	(*DeleteInstanceRequest)(nil),       // 4: api.v1.instance.DeleteInstanceRequest
	(*Instance)(nil),                    // 5: api.v1.instance.Instance
	(*DownloadCapturesRequest)(nil),     // 6: api.v1.instance.DownloadCapturesRequest
	(*CaptureChunk)(nil),                // 7: api.v1.instance.CaptureChunk
	(*ListCaptureSessionsRequest)(nil),  // 8: api.v1.instance.ListCaptureSessionsRequest
	(*ListCaptureSessionsResponse)(nil), // 9: api.v1.instance.ListCaptureSessionsResponse
	(*CaptureSessionInfo)(nil),          // 10: api.v1.instance.CaptureSessionInfo
	nil,                                 // 11: api.v1.instance.CreateInstanceRequest.AdditionalEntry
	nil,                                 // 12: api.v1.instance.Instance.AdditionalEntry
	(*timestamppb.Timestamp)(nil),       // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 14: google.protobuf.Empty
}
var file_api_v1_instance_instance_proto_depIdxs = []int32{
	11, // 0: api.v1.instance.CreateInstanceRequest.additional:type_name -> api.v1.instance.CreateInstanceRequest.AdditionalEntry
	13, // 1: api.v1.instance.Instance.since:type_name -> google.protobuf.Timestamp
	13, // 2: api.v1.instance.Instance.last_renew:type_name -> google.protobuf.Timestamp
	13, // 3: api.v1.instance.Instance.until:type_name -> google.protobuf.Timestamp
	12, // 4: api.v1.instance.Instance.additional:type_name -> api.v1.instance.Instance.AdditionalEntry
	10, // 5: api.v1.instance.ListCaptureSessionsResponse.sessions:type_name -> api.v1.instance.CaptureSessionInfo
	13, // 6: api.v1.instance.CaptureSessionInfo.start_time:type_name -> google.protobuf.Timestamp
	13, // 7: api.v1.instance.CaptureSessionInfo.end_time:type_name -> google.protobuf.Timestamp
	0,  // 8: api.v1.instance.InstanceManager.CreateInstance:input_type -> api.v1.instance.CreateInstanceRequest
	1,  // 9: api.v1.instance.InstanceManager.RetrieveInstance:input_type -> api.v1.instance.RetrieveInstanceRequest
	2,  // 10: api.v1.instance.InstanceManager.QueryInstance:input_type -> api.v1.instance.QueryInstanceRequest
	3,  // 11: api.v1.instance.InstanceManager.RenewInstance:input_type -> api.v1.instance.RenewInstanceRequest
	4,  // 12: api.v1.instance.InstanceManager.DeleteInstance:input_type -> api.v1.instance.DeleteInstanceRequest
	6,  // 13: api.v1.instance.InstanceManager.DownloadCaptures:input_type -> api.v1.instance.DownloadCapturesRequest
	8,  // 14: api.v1.instance.InstanceManager.ListCaptureSessions:input_type -> api.v1.instance.ListCaptureSessionsRequest
	5,  // 15: api.v1.instance.InstanceManager.CreateInstance:output_type -> api.v1.instance.Instance
	5,  // 16: api.v1.instance.InstanceManager.RetrieveInstance:output_type -> api.v1.instance.Instance
	5,  // 17: api.v1.instance.InstanceManager.QueryInstance:output_type -> api.v1.instance.Instance
	5,  // 18: api.v1.instance.InstanceManager.RenewInstance:output_type -> api.v1.instance.Instance
	14, // 19: api.v1.instance.InstanceManager.DeleteInstance:output_type -> google.protobuf.Empty
	7,  // 20: api.v1.instance.InstanceManager.DownloadCaptures:output_type -> api.v1.instance.CaptureChunk
	9,  // 21: api.v1.instance.InstanceManager.ListCaptureSessions:output_type -> api.v1.instance.ListCaptureSessionsResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_v1_instance_instance_proto_init() }
func file_api_v1_instance_instance_proto_init() {
	if File_api_v1_instance_instance_proto != nil {
		return
	}
	file_api_v1_instance_instance_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_instance_instance_proto_rawDesc), len(file_api_v1_instance_instance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_instance_instance_proto_goTypes,
		DependencyIndexes: file_api_v1_instance_instance_proto_depIdxs,
		MessageInfos:      file_api_v1_instance_instance_proto_msgTypes,
	}.Build()
	File_api_v1_instance_instance_proto = out.File
	file_api_v1_instance_instance_proto_goTypes = nil
	file_api_v1_instance_instance_proto_depIdxs = nil
}
